#include <msp430.h>

#include <libmsp/periph.h>

#include "capybara.h"

void capybara_config_pins()
{
    GPIO(LIBCAPYBARA_PORT_BOOST_SW, OUT) &= ~BIT(LIBCAPYBARA_PIN_BOOST_SW);
    GPIO(LIBCAPYBARA_PORT_BOOST_SW, DIR) |= BIT(LIBCAPYBARA_PIN_BOOST_SW);
    GPIO(LIBCAPYBARA_BANK_PORT_0_PORT,REN) &= ~BIT(LIBCAPYBARA_BANK_PORT_0_PIN);
    GPIO(LIBCAPYBARA_BANK_PORT_1_PORT,REN) &= ~BIT(LIBCAPYBARA_BANK_PORT_1_PIN);
    GPIO(LIBCAPYBARA_BANK_PORT_2_PORT,REN) &= ~BIT(LIBCAPYBARA_BANK_PORT_2_PIN);
    GPIO(LIBCAPYBARA_BANK_PORT_3_PORT,REN) &= ~BIT(LIBCAPYBARA_BANK_PORT_3_PIN);
} 
